// Turns a parsed Grokbot Package into video-kit files: script.md + scenes.js (a single
// cinematic photo-slideshow scene, images independent of caption line breaks), a knowledge
// doc archiving the package's verified narration/headlines/sources, and asset requests for
// any visual prompt without a supplied image (fulfilled later by the package job's image step).
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { addFile, addRequest } from "./assets.ts";
import type { Package } from "./pkg.ts";
import { matchImages, splitNarration } from "./pkg.ts";
import { projectDir, videoDir } from "./paths.ts";
import { loadProject } from "./project.ts";

export type IngestOptions = {
	imagesDir?: string;
	style?: string;
	voice?: string;
};

export type IngestResult = {
	video: string;
	dir: string;
	lines: number;
	imagesProvided: number;
	imagesToGenerate: number;
	musicPending: boolean;
};

function scriptFrontMatter(pkg: Package, o: IngestOptions): string {
	const rows = [`title: ${pkg.title.replace(/\n/g, " ")}`];
	if (o.style) rows.push(`style: ${o.style}`);
	if (o.voice) rows.push(`voice: ${o.voice}`);
	if (pkg.music) rows.push("music: bgmusic");
	return `---\n${rows.join("\n")}\n---`;
}

function buildScriptMd(pkg: Package, lines: string[], sourcePath: string, o: IngestOptions): string {
	const front = scriptFrontMatter(pkg, o);
	const musicNote = pkg.music ? `Music: ${pkg.music.label ?? pkg.music.url} — ${pkg.music.url}` : "Music: none supplied (style default preset)";
	const headlinesNote = pkg.headlines.length ? `Cover headlines (thumbnail/title candidates):\n${pkg.headlines.map((h) => `- ${h}`).join("\n")}` : "";
	return `${front}
# ${pkg.title}

Source: Grokbot package (${sourcePath}). Narration used as-is (facts pre-verified upstream, not rewritten here).
${musicNote}
${headlinesNote}

## Lines
${lines.map((l, i) => `${i + 1}. ${l}`).join("\n")}
`;
}

const js = (s: unknown) => JSON.stringify(s);

function buildScenesJs(pkg: Package, lines: string[], images: string[], lastLine: number): string {
	const hook = pkg.headlines[0] ?? null;
	return `// ---------- ${pkg.title} ----------
// Generated by \`bun vk package\` from a Grokbot content package: one photo per entry in
// IMAGES, each shown for an even slice of the whole runtime (Ken Burns). Images are NOT tied
// to caption line breaks: the narration is split into natural sentences for readable
// subtitles, independent of the (usually larger) number of visual prompts.
const IMAGES=[${images.map(js).join(",")}];
const HOOK=${js(hook)};
const LINES=[
${lines.map((t) => ` {t:${js(t)}},`).join("\n")}
];
function hookCard(t){
 if(!HOOK||t>4.4) return '';
 const op=t<1.1?eo(clamp(t/1.1)):1-eo(clamp((t-3.6)/.8));
 return \`<div class="abs st-serif" style="left:80px;right:80px;top:700px;text-align:center;color:#fff;font-size:92px;font-style:italic;line-height:1.1;opacity:\${op};text-shadow:0 4px 24px rgba(0,0,0,.6)">\${esc(HOOK)}</div>\`;
}
const S={
 story(lt,t,o){
  const slot=o.dur/IMAGES.length, i=Math.max(0,Math.min(IMAGES.length-1,Math.floor(t/slot)));
  let h=STORY.photo(IMAGES[i],t-i*slot,slot);
  h+=STORY.letterbox(t);
  h+=STORY.vignette(.45);
  h+=STORY.dip(t,{d:.6});
  h+=STORY.dipOut(t,o.dur,{d:1.2});
  h+=hookCard(t);
  h+=o.caps.map(c=>STORY.subtitle(lt,c)).join('');
  if(t>o.dur-2.6) h+=STORY.end(t,o.dur-2.4,{title:VK.brand.name});
  return h;
 },
};
const SPEC=[
 ['story',[0,${lastLine}],{}],
];
`;
}

/** Write the video's files and asset requests. Fast/synchronous: no TTS, no image generation, no network beyond copying local files. */
export function ingestPackage(project: string, video: string, pkg: Package, packageDir: string, sourcePath: string, o: IngestOptions = {}): IngestResult {
	loadProject(project); // throws if the project doesn't exist
	const dir = videoDir(project, video);
	if (existsSync(dir)) throw new Error(`${dir} already exists (pick another --video, or run \`bun vk package resume ${project} ${video}\`)`);
	mkdirSync(dir, { recursive: true });

	const lines = splitNarration(pkg.narration);
	if (!lines.length) throw new Error("narration produced 0 lines after splitting");

	writeFileSync(join(dir, "script.md"), buildScriptMd(pkg, lines, sourcePath, o));

	const visuals = [...pkg.visuals].sort((a, b) => a.id.localeCompare(b.id));
	const imageNames = visuals.map((v) => `img${v.id}`);
	writeFileSync(join(dir, "scenes.js"), buildScenesJs(pkg, lines, imageNames, lines.length - 1));

	const matched = matchImages(pkg.visuals, o.imagesDir, packageDir);
	let imagesProvided = 0;
	for (const v of visuals) {
		const name = `img${v.id}`;
		const file = matched.get(v.id);
		if (file) {
			addFile(project, file, { name, kind: "image", description: v.title, source: { type: "file", path: basename(file) } });
			imagesProvided++;
		} else {
			addRequest(project, { name, kind: "image", description: v.prompt || v.title, video });
		}
	}

	const kbDir = join(projectDir(project), "knowledge", "videos");
	mkdirSync(kbDir, { recursive: true });
	writeFileSync(
		join(kbDir, `${video}.md`),
		`# ${pkg.title}

Verified externally by the Grokbot package pipeline for \`${video}\`. Used as-is; do not add facts beyond this document when editing the script.

## Narración
${pkg.narration.trim()}

## Titulares de portada
${pkg.headlines.map((h) => `- ${h}`).join("\n") || "(none supplied)"}

## Música
${pkg.music ? `${pkg.music.label ?? ""} — ${pkg.music.url}` : "(none supplied)"}
`,
	);

	return {
		video,
		dir,
		lines: lines.length,
		imagesProvided,
		imagesToGenerate: visuals.length - imagesProvided,
		musicPending: !!pkg.music,
	};
}
