/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as ApiAssetSplatRouteImport } from './routes/api/asset.$'
import { Route as ApiAssetsProjectRouteImport } from './routes/api/assets.$project'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as ApiUploadRefProjectRouteImport } from './routes/api/upload-ref.$project'
import { Route as PProjectIndexRouteImport } from './routes/p.$project.index'
import { Route as PProjectSetupRouteImport } from './routes/p.$project.setup'
import { Route as StudioProjectVideoRouteImport } from './routes/studio.$project.$video'
import { Route as ApiPageProjectVideoRouteImport } from './routes/api/page.$project.$video'
import { Route as ApiUploadProjectNameRouteImport } from './routes/api/upload.$project.$name'
import { Route as PProjectVVideoRouteImport } from './routes/p.$project.v.$video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetSplatRoute = ApiAssetSplatRouteImport.update({
  id: '/api/asset/$',
  path: '/api/asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsProjectRoute = ApiAssetsProjectRouteImport.update({
  id: '/api/assets/$project',
  path: '/api/assets/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRefProjectRoute = ApiUploadRefProjectRouteImport.update({
  id: '/api/upload-ref/$project',
  path: '/api/upload-ref/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIndexRoute = PProjectIndexRouteImport.update({
  id: '/p/$project/',
  path: '/p/$project/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectSetupRoute = PProjectSetupRouteImport.update({
  id: '/p/$project/setup',
  path: '/p/$project/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectVideoRoute = StudioProjectVideoRouteImport.update({
  id: '/studio/$project/$video',
  path: '/studio/$project/$video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageProjectVideoRoute = ApiPageProjectVideoRouteImport.update({
  id: '/api/page/$project/$video',
  path: '/api/page/$project/$video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadProjectNameRoute = ApiUploadProjectNameRouteImport.update({
  id: '/api/upload/$project/$name',
  path: '/api/upload/$project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectVVideoRoute = PProjectVVideoRouteImport.update({
  id: '/p/$project/v/$video',
  path: '/p/$project/v/$video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/voices': typeof VoicesRoute
  '/studio/': typeof StudioIndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/assets/$project': typeof ApiAssetsProjectRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload-ref/$project': typeof ApiUploadRefProjectRoute
  '/p/$project/setup': typeof PProjectSetupRoute
  '/studio/$project/$video': typeof StudioProjectVideoRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/voices': typeof VoicesRoute
  '/studio': typeof StudioIndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/assets/$project': typeof ApiAssetsProjectRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload-ref/$project': typeof ApiUploadRefProjectRoute
  '/p/$project/setup': typeof PProjectSetupRoute
  '/studio/$project/$video': typeof StudioProjectVideoRoute
  '/p/$project': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/voices': typeof VoicesRoute
  '/studio/': typeof StudioIndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/assets/$project': typeof ApiAssetsProjectRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload-ref/$project': typeof ApiUploadRefProjectRoute
  '/p/$project/setup': typeof PProjectSetupRoute
  '/studio/$project/$video': typeof StudioProjectVideoRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/voices'
    | '/studio/'
    | '/api/asset/$'
    | '/api/assets/$project'
    | '/api/files/$'
    | '/api/upload-ref/$project'
    | '/p/$project/setup'
    | '/studio/$project/$video'
    | '/p/$project/'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/voices'
    | '/studio'
    | '/api/asset/$'
    | '/api/assets/$project'
    | '/api/files/$'
    | '/api/upload-ref/$project'
    | '/p/$project/setup'
    | '/studio/$project/$video'
    | '/p/$project'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/voices'
    | '/studio/'
    | '/api/asset/$'
    | '/api/assets/$project'
    | '/api/files/$'
    | '/api/upload-ref/$project'
    | '/p/$project/setup'
    | '/studio/$project/$video'
    | '/p/$project/'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  VoicesRoute: typeof VoicesRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiAssetSplatRoute: typeof ApiAssetSplatRoute
  ApiAssetsProjectRoute: typeof ApiAssetsProjectRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiUploadRefProjectRoute: typeof ApiUploadRefProjectRoute
  PProjectSetupRoute: typeof PProjectSetupRoute
  StudioProjectVideoRoute: typeof StudioProjectVideoRoute
  PProjectIndexRoute: typeof PProjectIndexRoute
  ApiPageProjectVideoRoute: typeof ApiPageProjectVideoRoute
  ApiUploadProjectNameRoute: typeof ApiUploadProjectNameRoute
  PProjectVVideoRoute: typeof PProjectVVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$': {
      id: '/api/asset/$'
      path: '/api/asset/$'
      fullPath: '/api/asset/$'
      preLoaderRoute: typeof ApiAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$project': {
      id: '/api/assets/$project'
      path: '/api/assets/$project'
      fullPath: '/api/assets/$project'
      preLoaderRoute: typeof ApiAssetsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-ref/$project': {
      id: '/api/upload-ref/$project'
      path: '/api/upload-ref/$project'
      fullPath: '/api/upload-ref/$project'
      preLoaderRoute: typeof ApiUploadRefProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/': {
      id: '/p/$project/'
      path: '/p/$project'
      fullPath: '/p/$project/'
      preLoaderRoute: typeof PProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/setup': {
      id: '/p/$project/setup'
      path: '/p/$project/setup'
      fullPath: '/p/$project/setup'
      preLoaderRoute: typeof PProjectSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$project/$video': {
      id: '/studio/$project/$video'
      path: '/studio/$project/$video'
      fullPath: '/studio/$project/$video'
      preLoaderRoute: typeof StudioProjectVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/page/$project/$video': {
      id: '/api/page/$project/$video'
      path: '/api/page/$project/$video'
      fullPath: '/api/page/$project/$video'
      preLoaderRoute: typeof ApiPageProjectVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/$project/$name': {
      id: '/api/upload/$project/$name'
      path: '/api/upload/$project/$name'
      fullPath: '/api/upload/$project/$name'
      preLoaderRoute: typeof ApiUploadProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/v/$video': {
      id: '/p/$project/v/$video'
      path: '/p/$project/v/$video'
      fullPath: '/p/$project/v/$video'
      preLoaderRoute: typeof PProjectVVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  VoicesRoute: VoicesRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiAssetSplatRoute: ApiAssetSplatRoute,
  ApiAssetsProjectRoute: ApiAssetsProjectRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiUploadRefProjectRoute: ApiUploadRefProjectRoute,
  PProjectSetupRoute: PProjectSetupRoute,
  StudioProjectVideoRoute: StudioProjectVideoRoute,
  PProjectIndexRoute: PProjectIndexRoute,
  ApiPageProjectVideoRoute: ApiPageProjectVideoRoute,
  ApiUploadProjectNameRoute: ApiUploadProjectNameRoute,
  PProjectVVideoRoute: PProjectVVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
